SELECT USER
FROM DUAL;

SELECT *
FROM TAB;

-- ○ 특정 『테이블명』을 참조하는 모든 테이블 목록 출력
SELECT FK.OWNER, FK.CONSTRAINT_NAME, FK.TABLE_NAME
FROM ALL_CONSTRAINTS FK, ALL_CONSTRAINTS PK
WHERE FK.R_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
  AND FK.CONSTRAINT_TYPE = 'R'
  AND PK.TABLE_NAME = UPPER('테이블명')
ORDER BY FK.TABLE_NAME;

-- ex)
SELECT FK.OWNER, FK.CONSTRAINT_NAME, FK.TABLE_NAME
FROM ALL_CONSTRAINTS FK, ALL_CONSTRAINTS PK
WHERE FK.R_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
  AND FK.CONSTRAINT_TYPE = 'R'
  AND PK.TABLE_NAME = UPPER('DEPARTMENTS')
ORDER BY FK.TABLE_NAME;
--==>>
/*
OWNER                          CONSTRAINT_NAME                TABLE_NAME                    
------------------------------ ------------------------------ ------------------------------
HR                             EMP_DEPT_FK                    EMPLOYEES                     
HR                             JHIST_DEPT_FK                  JOB_HISTORY                   

*/

SELECT FK.OWNER, FK.CONSTRAINT_NAME, FK.TABLE_NAME
FROM ALL_CONSTRAINTS FK, ALL_CONSTRAINTS PK
WHERE FK.R_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
  AND FK.CONSTRAINT_TYPE = 'R'
  AND PK.TABLE_NAME = UPPER('EMPLOYEES')
ORDER BY FK.TABLE_NAME;
--==>>
/*

OWNER                          CONSTRAINT_NAME                TABLE_NAME                    
------------------------------ ------------------------------ ------------------------------
HR                             DEPT_MGR_FK                    DEPARTMENTS                   
HR                             EMP_MANAGER_FK                 EMPLOYEES                     
HR                             JHIST_EMP_FK                   JOB_HISTORY                   

*/


-- ○ 특정 『테이블명』이 참조하고 있는 모든 테이블 목록 출력
SELECT TABLE_NAME
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME IN (SELECT R_CONSTRAINT_NAME
                            FROM USER_CONSTRAINTS
                            WHERE TABLE_NAME = UPPER('테이블명')
                            AND CONSTRAINT_TYPE = 'R');


SELECT TABLE_NAME
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME IN (SELECT R_CONSTRAINT_NAME
                            FROM USER_CONSTRAINTS
                            WHERE TABLE_NAME = UPPER('EMPLOYEES')
                            AND CONSTRAINT_TYPE = 'R');

--==>>
/*

TABLE_NAME                    
------------------------------
JOBS
EMPLOYEES
DEPARTMENTS

*/


-- ■■■ 팀별 실습 과제 ■■■ --

-- HR 샘플 스키마 ERD를 이용한 테이블 재구성

-- 팀별로 HR 스키마에 있는 기본 테이블(7개)
-- COUNTRIES / DEPARTMENTS / EMPLOYEES / JOBS / JOB_HISTORY / LOCATIONS / REGIONS
-- 을 똑같이 새로 구성한다.

-- 단, 생성하는 테이블의 이름은 『테이블명+팀번호』
-- 1팀: COUNTRIES1 / DEPARTMENTS1 / EMPLOYEES1 / JOBS1 / JOB_HISTORY1 / LOCATIONS1 / REGIONS1
-- 과 같이 구성한다.

-- 1. 기존 테이블의 정보 수집
-- 2. 테이블 생성 (→ 컬럼명, 자료형, DEFAULT 표현식, NOT NULL 등)
--    제약조건 설정(→ PK, U, FK, CK, .... , NN) (제약조건명 이름은 배운대로)
-- 3. 데이터 입력
-- 4. 제출 항목
--    - 1팀: 20260112_02_hr_팀별실습과제_1.sql
--    - 1팀: 후기_1.sql

SELECT *
FROM COUNTRIES;

DESC COUNTRIES;

SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'COUNTRIES';





SELECT *
FROM JOB_HISTORY;
DESC JOB_HISTORY;

SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'JOB_HISTORY';

SELECT *
FROM JOBS;
DESC JOBS;

SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'JOBS';

SELECT *
FROM EMPLOYEES;
DESC EMPLOYEES;


SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'EMPLOYEES';

SELECT *
FROM  DEPARTMENTS;
DESC DEPARTMENTS;

SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'DEPARTMENTS';



----------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------ LOCATIONS
SELECT *
FROM LOCATIONS;

DESC LOCATIONS;

SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'LOCATIONS';



-- 테이블생성
-- 테이블명: LOCATIONS1
CREATE TABLE LOCATIONS1
( LOCATION_ID       NUMBER(4)
, STREET_ADDRESS    VARCHAR2(40)
, POSTAL_CODE       VARCHAR2(12)
, CITY              VARCHAR2(30) CONSTRAINT LOC_CITY_NN  NOT NULL
, STATE_PROVINCE    VARCHAR2(25)
, COUNTRY_ID        CHAR(2)
);

-- 제약조건 추가
ALTER TABLE LOCATIONS1
ADD (CONSTRAINT LOC_ID_PK PRIMARY KEY(LOCATION_ID)
    ,CONSTRAINT LOC_C_ID_FK FOREIGN KEY(COUNTRY_ID)
                 REFERENCES COUNTRIES(COUNTRY_ID));

ALTER TABLE LOCATIONS1
MODIFY (CONSTRAINTS LOC_CITY_NN NOT NULL);



--- 데이터 입력
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(1000, '1297 Via Cola di Rie', '00989', 'Roma', NULL, 'IT');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(1100, '93091 Calle della Testa', '10934', 'Venice', NULL, 'IT');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(1200, '2017 Shinjuku-ku', '1689', 'Tokyo', Tokyo Prefecture, 'JP');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(1300, '9450 Kamiya-cho', '6823', 'Hiroshima', NULL, 'JP');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(1400, '2014 Jabberwocky Rd', '26192', 'Southlake', 'Texas', 'US');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(1500, '2011 Interiors Blvd', '99236', 'South San Francisco', 'California', 'US');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(1600, '2007 Zagora St', '50090', 'South Brunswick', 'New Jersey', 'US');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(1700, '2004 Charade Rd', '98199', 'Seattle', 'Washington', 'US');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(1800, '147 Spadina Ave', 'M5V 2L7', 'Toronto', 'Ontario', 'CA');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(1900, '6092 Boxwood St', 'YSW 9T2', 'Whitehorse', 'Yukon', 'CA');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(2000, '40-5-12 Laogianggen', '190518', 'Beijing', NULL, 'CN');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(2100, '1298 Vileparle (E)', '490231', 'Bombay', 'Maharashtra', 'IN');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(2200, '12-98 Victoria Street', '2901', 'Sydney', 'New South Wales', 'AU');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(2300, '198 Clementi North', '540198', 'Singapore', NULL, 'SG');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(2400, '8204 Arthur St', NULL, 'London', NULL, 'UK');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(2500, 'Magdalen Centre, The Oxford Science Park', 'OX9 9ZB', 'Oxford', 'Oxford', 'UK');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(2600, '9702 Chester Road', '09629850293', 'Stretford', 'Manchester', 'UK');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(2700, 'Schwanthalerstr. 7031', '80925', 'Munich', 'Bavaria', 'DE');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(2800, 'Rua Frei Caneca 1360', '01307-002', 'Sao Paulo', 'Sao Paulo', 'BR');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(2900, '20 Rue des Corps-Saints', '1730', 'Geneva', 'Geneva', 'CH');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(3000, 'Murtenstrasse 921', '3095', 'Bern', 'BE', 'CH');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(3100, 'Pieter Breughelstraat 837', '3029SK', 'Utrecht', 'Utrecht', 'NL');
INSERT INTO LOCATIONS1(LOCATION_ID, STREET_ADDRESS, PORSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES(3200, 'Mariano Escobedo 9991', '11932', 'Mexico City', 'Distrito Federal,', 'MX');

----------------------------------------------------------------- REGIONS

SELECT *
FROM REGIONS;

DESC REGIONS;

SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'REGIONS';

-- 테이블생성
-- 테이블명: REGIONS1
CREATE TABLE REGIONS1
( REGION_ID     NUMBER CONSTRAINT REGION_ID_NN NOT NULL
, REGION_NAME   VARCHAR2(25)
);

-- 제약조건 추가
ALTER TABLE REGIONS1
ADD (CONSTRAINT REG_ID_PK PRIMARY KEY(REGION_ID));



-- 데이터 입력
INSERT INTO REGIONS1(REGION_ID, REGION_NAME) VALUES(1, 'Europe');
INSERT INTO REGIONS1(REGION_ID, REGION_NAME) VALUES(2, 'Americas');
INSERT INTO REGIONS1(REGION_ID, REGION_NAME) VALUES(3, 'Asia');
INSERT INTO REGIONS1(REGION_ID, REGION_NAME) VALUES(4, 'Middle East and Africa');









